auto commit

diff --git a/conky-check b/conky-check
--- a/conky-check
+++ b/conky-check
@@ -4,22 +4,59 @@ echo
 echo "Checking dependencies. . ."
 echo
 sleep 2
-if ! dpkg --get-selections | awk '{print $1}' | grep -x "xterm"; then
+if ! dpkg --get-selections | awk '{print $1}' | grep -xq "xterm"; then
+	echo "xterm not found, installing now. . ."
+	sleep 1
 	sudo apt install xterm
+else
+	echo "xterm found."
+	sleep 1
 fi
-if ! dpkg --get-selections | awk '{print $1}' | grep -x "conky"; then
+if ! dpkg --get-selections | awk '{print $1}' | grep -xq "conky"; then
+	echo "conky not found, installing now. . ."
+	sleep 1
 	sudo apt install conky
+else
+	echo "conky found."
+	sleep 1
 fi
 
-sleep 10; xterm -e "zsh -c \"/home/msifland/scripts/conky_start\""
-
+sleep 2
+echo
+echo "Making sure conky is not running..."
+sleep 1
+cpid=$(pidof conky)
+while [[ $cpid != "" ]]; do
+	echo "Shutting down conky. . ."
+	echo "PID="$cpid
+	cpid=$(pidof conky)
+	killall conky
+	sleep 1
+done
 
 echo
-echo "Checking ethernet or wireless connections. . ."
+echo "Checking for ethernet or wireless connections. . ."
 echo
 sleep 2
 
 $HOME/scripts/conky_iface_var.sh
+
+echo
+echo 'Starting conky in:'
+# Start a countdown to action.
+secs=$((1 * 30))
+while [ $secs -gt 0 ]; do
+   echo -ne "$secs\033[0K\r"
+   sleep 1
+   : $((secs--))
+done
+
+# Start conky
+echo "Starting conky now. . ."
+conky
+sleep 10
+# Kill current terminal that this process is running in.
+kill -9 $PPID
 
 if [ $? -eq 0 ]; then
 	echo
