auto commit

diff --git a/kernel_scripts/kernel-check b/kernel_scripts/kernel-check
--- a/kernel_scripts/kernel-check
+++ b/kernel_scripts/kernel-check
@@ -54,163 +54,101 @@ echo -e "${ILRESTORE}"
 # Calling function to check versions.
 if version_gt "$GET_VER" "$CURNT"; then
 	# Added this because of automation this stops the screen for a response when called with the script kern-update-timer.
-	if dialog --yesno "There is a newer kernel available.
-You are running $CURNT, and $GET_VER is out.
-Would you like to install it?" 10 50; then
-		# Start timing process
-		tm_wh_start=$(date +"%s")
-		clear
+	# Start timing process
+	tm_wh_start=$(date +"%s")
+	clear
 
-		echo
-		sleep 1
-		# Formatting for web search.
-		echo "${ILCOLOR2}Downloding latest kernel now. . .${ILRESTORE}"
-		wget $GET
-		echo
+	echo
+	sleep 1
+	# Formatting for web search.
+	echo "${ILCOLOR2}Downloding latest kernel now. . .${ILRESTORE}"
+	wget $GET
+	echo
 
-		echo "${ILCOLOR2}Unzipping kernel. . .${ILRESTORE}"
-		sleep 1
-		tar -xf linux-"$GET_VER".tar.xz
-		echo
+	echo "${ILCOLOR2}Unzipping kernel. . .${ILRESTORE}"
+	sleep 1
+	tar -xf linux-"$GET_VER".tar.xz
+	echo
 
-		echo "${ILCOLOR2}Checking dependencies. . .${ILRESTORE}"
-		echo 'spike' | sudo -S apt build-dep -y linux
-		echo 'spike' | sudo -S apt install ncurses-dev fakeroot
-		cd linux-"$GET_VER"
-		echo
+	echo "${ILCOLOR2}Checking dependencies. . .${ILRESTORE}"
+	echo 'spike' | sudo -S apt build-dep -y linux
+	echo 'spike' | sudo -S apt install ncurses-dev fakeroot
+	cd linux-"$GET_VER"
+	echo
 
-		CURR_STAB=$(ls /boot | grep "config" | sort -g | head -1)
-		echo "${ILCOLOR2}Copying current STABLE kernel - ${ILRESTORE}$CURR_STAB. . ."
-		cp /boot/$CURR_STAB .config
-		echo
+	CURR_STAB=$(ls /boot | grep "config" | sort -g | head -1)
+	echo "${ILCOLOR2}Copying current STABLE kernel - ${ILRESTORE}$CURR_STAB. . ."
+	cp /boot/$CURR_STAB .config
+	echo
 
-		# This section is if you want to add an option the choose a local verson name to append to kernel version.
-<< Comment
-		echo "${ILCOLOR2}Append to Kernel Number for Local Version name.
-    Current running kernel:${ILRESTORE} $(uname -r)"
-		CONF_VER=$(grep 'CONFIG_LOCALVERSION="' .config | cut -d'=' -f2 | sed 's:"::g')
-		echo
-		echo "${ILCOLOR2}Local version from .config file:${ILRESTORE} $CONF_VER"
-		echo
-		
-		read -p "  Leave blank for same as STABLE. A dash will be appended before custom version.('Enter' for blank, or '0' to remove custom version altogether.)? " LOC_VER
-		# If using kernel .config from local machine and it already has an appended version, this captures that appended version to add to initramfs update below, otherwise modules folder name will not match kernel name.
-		if [[ "$LOC_VER" != "" ]]; then
-			sed -i "/CONFIG_LOCALVERSION=/c\CONFIG_LOCALVERSION=\"-$LOC_VER\"" .config
-		fi
-		if [[ "$LOC_VER" = "0" ]]; then
-			sed -i "s:CONFIG_LOCALVERSION=.*:CONFIG_LOCALVERSION=\"\":g" .config
-		fi
-Comment
+	scripts/config --disable DEBUG_INFO
+	echo "${ILCOLOR2}Appending '-msi' to kernel version to show as custom built kernel."
+	# This is local version appended to kernel
+	LOC_VER="-msi"
+	echo "sed -i \"/CONFIG_LOCALVERSION=/c\CONFIG_LOCALVERSION=\"$LOC_VER\"" .config
+	sed -i "/CONFIG_LOCALVERSION=/c\CONFIG_LOCALVERSION=\"$LOC_VER\"" .config
+	sleep 1
 
-		scripts/config --disable DEBUG_INFO
-		echo "${ILCOLOR2}Appending '-msi' to kernel version to show as custom built kernel."
-		# This is local version appended to kernel
-		LOC_VER="-msi"
-		echo "sed -i \"/CONFIG_LOCALVERSION=/c\CONFIG_LOCALVERSION=\"$LOC_VER\"" .config
-		sed -i "/CONFIG_LOCALVERSION=/c\CONFIG_LOCALVERSION=\"$LOC_VER\"" .config
-		sleep 1
-
-		echo
-		echo "${ILCOLOR2}Removing \"CONFIG_SYSTEM_TRUSTED_KEYS=\" from .config${ILRESTORE}"
-		if grep -w "^CONFIG_SYSTEM_TRUSTED_KEYS=" .config; then
-			sed -i 's:CONFIG_SYSTEM_TRUSTED_KEYS=:#CONFIG_SYSTEM_TRUSTED_KEYS=:g' .config
-		fi
-
-		# Command 'oldefconfig' pulls current options from .config file and automatically answers new options without prompt.
-		make olddefconfig
-		#make menuconfig
-		make -j `getconf _NPROCESSORS_ONLN` deb-pkg
-		echo 'spike' | sudo -S make modules_install
-
-		# This variable is here before we change out of this directory, for initramfs update format below.
-		CONF_VER_WRT=$(grep 'CONFIG_LOCALVERSION="' .config | cut -d'=' -f2 | sed 's:"::g')
-
-		# Installing kernel and updateing grub and initramfs
-		cd ..
-		echo 'spike' | sudo -S dpkg -i *.deb
-		echo 'spike' | sudo -S update-initramfs -c -t -k "$GET_VER$CONF_VER_WRT"
-		echo 'spike' | sudo -S update-grub		
-		sleep 1
-
-		# End timing process
-		tm_wh_end=$(date +"%s")
-		tm_wh_diff=$(( $tm_wh_end - $tm_wh_start))
-		echo
-		echo "${ILCOLOR2}It took $(($tm_wh_diff / 3600 )) hours $((($tm_wh_diff % 3600) / 60)) minutes $(($tm_wh_diff % 60)) seconds to run whole process.${ILRESTORE}"
-
-<< Comment
-		# Build perf package
-		export WORK_DIR="$WORK_DIR"
-		export GET="$GET_VER"
-		sleep 1
-		echo
-		echo "${ILCOLOR2}Now building perf package(Linux-tools). . .${ILRESTORE}"
-
-		# Copy script to current directory to build.
-		cp $HOME/scripts/kernel_scripts/perf-build $WORK_DIR/linux-$GET_VER/perf-build
-		cd $WORK_DIR/linux-$GET_VER
-		sed -i "s:VERSION=\"\":VERSION=\"$GET_VER\":g" perf-build		
-		xterm -e "bash -c \"cd $WORK_DIR/linux-$GET_VER; ./perf-build; echo; echo;\""
-		cd ..
-		echo 'spike' | sudo -S apt purge -y "linux-perf*"
-		echo 'spike' | sudo -S dpkg -i --force-all $HOME/tmp/perf-package/*.deb
-		if ls $HOME/tmp/perf-package/*.deb >/dev/null 2>&1; then
-			cp $HOME/tmp/perf-package/*.deb $HOME/tmp/kernel_storage
-		fi
-		if [[ -d $HOME/tmp/perf-package ]]; then
-			rm -rf $HOME/tmp/perf-package
-		fi
-Comment
-
-		# This section is for if you are using nvidia drivers.
-<< Comment
-		# Build nvidia-kernel at boot
-		if ! dpkg --get-selections | awk '{print $1}' | grep -wq "module-assistant"; then
-			sudo apt -y install module-assistant
-		fi
-
-		# If using nvidia drivers.
-		$HOME/scripts/kernel_scripts/nvidia-build
-Comment
-		
-		# Reboot to new kernel?
-		YNRBT="y"
-		read -p "Would you like to reboot to new kernel now?[Y/n] " YNRBT
-		echo
-		if [[ "$YNRBT" =~ ^([yY][eE][sS]|[yY])$ ]]; then
-			cd ..
-			# Create kernel storage directory if doesn't exist, for storage of previously built kernels.
-			if [[ ! -d $STOR_DIR ]]; then
-				mkdir $STOR_DIR
-			fi
-
-			# Error handling if directory exists but is empty. Using ls instead of [[ -f ]] for wildcards.
-			if [[ $(ls $STOR_DIR) ]]; then
-				ls $STOR_DIR/* -t | tail -n +22 | xargs rm -f
-			fi
-
-			# Clean up.
-			if [[ -d "$WORK_DIR" ]]; then
-				if ls $WORK_DIR/*.deb > /dev/null 2>&1; then
-					cp $WORK_DIR/*.deb $STOR_DIR
-				fi
-				rm -rf "$WORK_DIR"
-			fi
-
-			cd $HOME
-			echo 'spike' | sudo -S shutdown -r now
-		else
-			echo "Ok, not rebooting now."
-			echo
-			sleep 1
-		fi
-	else
-		clear
-		echo "${ILCOLOR2}Ok, not installing now, re-run script to install latest kernel.${ILRESTORE}"
-		echo
-		sleep 3
+	echo
+	echo "${ILCOLOR2}Removing \"CONFIG_SYSTEM_TRUSTED_KEYS=\" from .config${ILRESTORE}"
+	if grep -w "^CONFIG_SYSTEM_TRUSTED_KEYS=" .config; then
+		sed -i 's:CONFIG_SYSTEM_TRUSTED_KEYS=:#CONFIG_SYSTEM_TRUSTED_KEYS=:g' .config
 	fi
+
+	# Command 'oldefconfig' pulls current options from .config file and automatically answers new options without prompt.
+	make olddefconfig
+	#make menuconfig
+	make -j `getconf _NPROCESSORS_ONLN` deb-pkg
+	echo 'spike' | sudo -S make modules_install
+
+	# This variable is here before we change out of this directory, for initramfs update format below.
+	CONF_VER_WRT=$(grep 'CONFIG_LOCALVERSION="' .config | cut -d'=' -f2 | sed 's:"::g')
+
+	# Installing kernel and updateing grub and initramfs
+	cd ..
+	echo 'spike' | sudo -S dpkg -i *.deb
+	echo 'spike' | sudo -S update-initramfs -c -t -k "$GET_VER$CONF_VER_WRT"
+	echo 'spike' | sudo -S update-grub		
+	sleep 1
+
+	# End timing process
+	tm_wh_end=$(date +"%s")
+	tm_wh_diff=$(( $tm_wh_end - $tm_wh_start))
+	echo
+	echo "${ILCOLOR2}It took $(($tm_wh_diff / 3600 )) hours $((($tm_wh_diff % 3600) / 60)) minutes $(($tm_wh_diff % 60)) seconds to run whole process.${ILRESTORE}"
+
+	# This section is for if you are using nvidia drivers.
+<< Comment
+	# Build nvidia-kernel at boot
+	if ! dpkg --get-selections | awk '{print $1}' | grep -wq "module-assistant"; then
+		sudo apt -y install module-assistant
+	fi
+
+	# If using nvidia drivers.
+	$HOME/scripts/kernel_scripts/nvidia-build
+Comment
+		
+	# Reboot to new kernel
+	cd ..
+	# Create kernel storage directory if doesn't exist, for storage of previously built kernels.
+	if [[ ! -d $STOR_DIR ]]; then
+		mkdir $STOR_DIR
+	fi
+
+	# Error handling if directory exists but is empty. Using ls instead of [[ -f ]] for wildcards.
+	if [[ $(ls $STOR_DIR) ]]; then
+		ls $STOR_DIR/* -t | tail -n +22 | xargs rm -f
+	fi
+
+	# Clean up.
+	if [[ -d "$WORK_DIR" ]]; then
+		if ls $WORK_DIR/*.deb > /dev/null 2>&1; then
+			cp $WORK_DIR/*.deb $STOR_DIR
+		fi
+		rm -rf "$WORK_DIR"
+	fi
+		cd $HOME
+		echo 'spike' | sudo -S shutdown -r now
 else
 	echo "${ILCOLOR2}You already have the latest kernel.${ILRESTORE}"
 	echo
