auto commit

diff --git a/install-debian/debian-install-single-part b/install-debian/debian-install-single-part
--- a/install-debian/debian-install-single-part
+++ b/install-debian/debian-install-single-part
@@ -137,13 +137,15 @@ rm -f "$INST_PTH"/{debian-install-continue,my_packs.list.chroot}
 # -------------------------- Handle separate partitions ------------#
 # Clear existing fstab or add a header
 echo "			###### msifland custom install script ######" > "$INST_PTH/etc/fstab" || true
+# Get the UUID of the target partition
+ROOT_UUID=$(blkid -s UUID -o value "$TARGET_DISK")
 echo "" >> "$INST_PTH/etc/fstab" || true
 echo "" >> "$INST_PTH/etc/fstab" || true
-echo "UUID=#####UUID HERE#####  / ext4 defaults,errors=remount-ro	0   1" >> "$INST_PTH/etc/fstab" || true
+echo "UUID=$ROOT_UUID  / ext4 defaults,errors=remount-ro	0   1" >> "$INST_PTH/etc/fstab" || true
 
 # --- Add the EFI partition ---
 echo
-echo "Add new partition to fstab"
+echo "Added new partition to fstab. Opening for review and double-check."
 sleep 1
 xterm -hold -e "lsblk -f -p" &
 nano "$INST_PTH/etc/fstab"
