auto commit

diff --git a/install-debian/debian-install-single-part b/install-debian/debian-install-single-part
--- a/install-debian/debian-install-single-part
+++ b/install-debian/debian-install-single-part
@@ -135,14 +135,17 @@ rm -f "$INST_PTH"/{debian-install-continue,my_packs.list.chroot}
 
 # -------------------------- Handle separate partitions ------------#
 # Clear existing fstab or add a header
-echo "###### msifland custom install script ######" > "$INST_PTH/etc/fstab" || true
+echo "			###### msifland custom install script ######" > "$INST_PTH/etc/fstab" || true
+echo "" >> "$INST_PTH/etc/fstab" || true
+echo "" >> "$INST_PTH/etc/fstab" || true
+echo "UUID=#####UUID HERE#####  / ext4 defaults,errors=remount-ro	0   1" >> "$INST_PTH/etc/fstab" || true
 
 # --- Add the EFI partition ---
 echo
 echo "Add new partition to fstab"
 sleep 1
 lsblk
-subl "$INST_PTH/etc/fstab"
+sudo nano "$INST_PTH/etc/fstab"
 
 # -------------------------- Copy user data ------------------------#
 usrnme=$(cat "$INST_PTH/usrnme.txt" 2>/dev/null || echo "user")
